A= crea_arbol()
A= inserta(A,"diminuto")
A= inserta(A,"peque~no")
A= inserta(A,"mediano")
A= inserta(A,"grande")
A= inserta(A,"diminuto")
print A
print pertenece(A,"´infimo")
print pertenece(A,"grande")